name: .NET RoomBooking

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install SonarScanner CLI
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Install dotnet coverage tool
      run: dotnet tool install --global dotnet-coverage

    - name: Restore dependencies
      run: dotnet restore

    - name: Collect coverage manually
      run: |
        dotnet build
        dotnet-coverage collect "dotnet test" -f cobertura -o "TestResults/coverage.cobertura.xml"

    - name: Print coverage report
      run: cat ./TestResults/coverage.cobertura.xml

    - name: Begin SonarCloud Analysis
      run: dotnet sonarscanner begin /k:"pyankov00_RoomBookingApp.Unwe" /o:"pyankov00" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.coverageReportPaths="./TestResults/**/coverage.cobertura.xml"

    - name: Build for SonarCloud
      run: dotnet build --no-incremental

    - name: End SonarCloud Analysis
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: TestResults
        path: ./TestResults
